name: Deploy Database Models

on:
  push:
    branches: [ main ]
    paths:
      - '*.sql'
  workflow_dispatch:
    inputs:
      models:
        description: 'Models to deploy'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - modelo01
          - modelo02
          - modelo03

env:
  SQL_SERVER: 'serverlab03.database.windows.net'
  SQL_USER: 'fabiola'

jobs:
  deploy-models:
    name: Deploy SQL Models
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install SQL Tools
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y mssql-tools

    - name: Deploy Modelo01
      if: github.event.inputs.models == 'all' || github.event.inputs.models == 'modelo01' || github.event.inputs.models == ''
      run: |
        echo "🚀 Deploying modelo01.sql to modelo01_envios..."
        /opt/mssql-tools/bin/sqlcmd -S $SQL_SERVER -d modelo01_envios -U $SQL_USER -P "${{ secrets.SQL_ADMIN_PASSWORD }}" -i modelo01.sql -b
        echo "✅ Modelo01 deployed successfully!"

    - name: Deploy Modelo02
      if: github.event.inputs.models == 'all' || github.event.inputs.models == 'modelo02' || github.event.inputs.models == ''
      run: |
        echo "🚀 Deploying modelo02.sql to modelo02_reservas..."
        /opt/mssql-tools/bin/sqlcmd -S $SQL_SERVER -d modelo02_reservas -U $SQL_USER -P "${{ secrets.SQL_ADMIN_PASSWORD }}" -i modelo02.sql -b
        echo "✅ Modelo02 deployed successfully!"

    - name: Deploy Modelo03
      if: github.event.inputs.models == 'all' || github.event.inputs.models == 'modelo03' || github.event.inputs.models == ''
      run: |
        echo "🚀 Deploying modelo03.sql to modelo03_adicional..."
        /opt/mssql-tools/bin/sqlcmd -S $SQL_SERVER -d modelo03_adicional -U $SQL_USER -P "${{ secrets.SQL_ADMIN_PASSWORD }}" -i modelo03.sql -b
        echo "✅ Modelo03 deployed successfully!"

    - name: Deployment Summary
      run: |
        echo "🎉 Database models deployment completed!"
        echo "📊 Models deployed to:"
        echo "  - modelo01_envios (Shipping model)"
        echo "  - modelo02_reservas (Travel reservations model)" 
        echo "  - modelo03_adicional (Additional model)"
        echo "🔗 Server: $SQL_SERVER"