name: Deploy Database Models with Liquibase

on:
  push:
    branches: [ main ]
    paths:
      - '*.sql'
  workflow_dispatch:
    inputs:
      models:
        description: 'Models to deploy'
        required: true
        default: 'all'
        type: choice
        options:
          - modelo01
          - modelo02
          - modelo03

env:
  SQL_SERVER: 'serverlab03.database.windows.net'
  SQL_USER: 'fabiola'
  LIQUIBASE_VERSION: '4.25.1'

jobs:
  deploy-models:
    name: Deploy SQL Models with Liquibase
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Java for Liquibase
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download Liquibase
      run: |
        wget https://github.com/liquibase/liquibase/releases/download/v${{ env.LIQUIBASE_VERSION }}/liquibase-${{ env.LIQUIBASE_VERSION }}.tar.gz
        tar -xzf liquibase-${{ env.LIQUIBASE_VERSION }}.tar.gz
        chmod +x liquibase

    - name: Download SQL Server JDBC Driver
      run: |
        wget https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/12.4.2.jre11/mssql-jdbc-12.4.2.jre11.jar
        mkdir -p jdbc
        mv mssql-jdbc-12.4.2.jre11.jar jdbc/

    - name: Deploy Modelo01 with Liquibase
      run: |
        echo "🚀 Deploying modelo01.sql to modelo01_envios using Liquibase..."
        ./liquibase \
          --driver=com.microsoft.sqlserver.jdbc.SQLServerDriver \
          --classpath=jdbc/mssql-jdbc-12.4.2.jre11.jar \
          --changeLogFile=modelo01.sql \
          --url="jdbc:sqlserver://$SQL_SERVER:1433;database=modelo01_envios;encrypt=true;trustServerCertificate=true;" \
          --username=$SQL_USER \
          --password="${{ secrets.SQL_ADMIN_PASSWORD }}" \
          update
        echo "✅ Modelo01 deployed successfully with Liquibase!"

    - name: Deploy Modelo02 with Liquibase
      run: |
        echo "🚀 Deploying modelo02.sql to modelo02_reservas using Liquibase..."
        ./liquibase \
          --driver=com.microsoft.sqlserver.jdbc.SQLServerDriver \
          --classpath=jdbc/mssql-jdbc-12.4.2.jre11.jar \
          --changeLogFile=modelo02.sql \
          --url="jdbc:sqlserver://$SQL_SERVER:1433;database=modelo02_reservas;encrypt=true;trustServerCertificate=true;" \
          --username=$SQL_USER \
          --password="${{ secrets.SQL_ADMIN_PASSWORD }}" \
          update
        echo "✅ Modelo02 deployed successfully with Liquibase!"

    - name: Deploy Modelo03 with Liquibase
      run: |
        echo "🚀 Deploying modelo03.sql to modelo03_adicional using Liquibase..."
        ./liquibase \
          --driver=com.microsoft.sqlserver.jdbc.SQLServerDriver \
          --classpath=jdbc/mssql-jdbc-12.4.2.jre11.jar \
          --changeLogFile=modelo03.sql \
          --url="jdbc:sqlserver://$SQL_SERVER:1433;database=modelo03_adicional;encrypt=true;trustServerCertificate=true;" \
          --username=$SQL_USER \
          --password="${{ secrets.SQL_ADMIN_PASSWORD }}" \
          update
        echo "✅ Modelo03 deployed successfully with Liquibase!"

    - name: Deployment Summary
      run: |
        echo "🎉 Database models deployment completed with Liquibase!"
        echo "📊 Models deployed to:"
        echo "  - modelo01_envios (Shipping model)"
        echo "  - modelo02_reservas (Travel reservations model)" 
        echo "  - modelo03_adicional (Additional model)"
        echo "🔗 Server: $SQL_SERVER"
        echo "🛠️ Tool: Liquibase v${{ env.LIQUIBASE_VERSION }}"